const names = require("./4-names");
const sayHi = require("./5-utils");
const data = require("./6-alternative-syntax");
require("./7-mind-grenade");
// console.log(data);
// console.log(names);
// console.log(sayHi);
// sayHi("palav");
// sayHi(names.name1);
// sayHi(names.name2);
